### ISSUE TITLE
GET /static/js/django_search_model.js HTTP/1.1" 404 1688

### ISSUE THREAD

**Issue by akohli96** [SchroterQuentin/django-search-listview#1]
I keep getting a 404. 

Here is my class

class MusiciansList(SearchableListView):
	model = Musicians
	#context_object_name = 'musicians'
	paginate_by = 10
	template_name = "notownapp/musicians_list.html"
	searchable_fields = ["ssn","name"]
	specifications = {
		"ssn":"__icontains"
	}

template

{% load staticfiles %}
<html>
    <head>
        <title>Musicians</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"> </script>
    </head>

<body>
<div class="row">
  {% include "search_listview/search_and_page.html" %}
</div>

</body>
<script src="{% static 'js/django_search_model.js' %}"></script>
<script>
    start_search()
</script>

</html>

I have installed the package and put it into my settings

**Comment by 0xteo** [comment]
The name of the used javascript file in the README is wrong. What you should load in your templates is this:
```html
<script src="{% static 'js/search_listview.js' %}"></script>
```
instead of 
```html
<script src="{% static 'js/django_search_model.js' %}"></script>
```

It would be a good idea to rename the js file to what is used in the README. @SchroterQuentin

**Comment by akohli96** [comment]
Thank you @TeodorIvanov

**Comment by SchroterQuentin** [comment]
I fix this typo and change the path to the file. In the last release (on Github & Pypi) it's now :

```html
<script src="{% static 'search_listview/js/search_listview.js' %}"></script>
```

Thank's for this notice

**Comment by akohli96** [comment]
Thank you @SchroterQuentin
