### ISSUE TITLE
Translatable search submit button

### ISSUE THREAD

**Issue by 0xteo** [SchroterQuentin/django-search-listview#2]
The [search_box.html template](https://github.com/SchroterQuentin/django-search-listview/blob/master/search_listview/templates/search_listview/search_box.html) should include an i18n trans tag around the submit button text.

**Comment by SchroterQuentin** [comment]
I agree. I just fix that right now. Thanks

**Comment by SchroterQuentin** [comment]
c013c5d6e350d7b40e58519449171ea0aa5bcf83
